az_resource_group_name="LearningDeployment"
az_storage_account_name="tfdevopsstorage"
az_container_name="tfstatedevops"
environment="test"
auth0_client_id=""
auth0_client_secret=""
auth0_domain="dev-i5eh5nau.us.auth0.com"