name: 'Terraform'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform TEST'
    runs-on: ubuntu-latest
    environment: TEST
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      STORAGE_ACCOUNT: tfdevopsstorage
      CONTAINER_NAME: tfstatecontainer-test
      ENVIRONMENT: TEST

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: "./"
        args:
          --backend-config="storage_account_name=${{ env.STORAGE_ACCOUNT }}"
          --backend-config="container_name=${{ env.CONTAINER_NAME }}"
          -var "environment=${{ env.ENVIRONMENT }}"

    - name: 'Terraform Validate'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'validate'
        tf_actions_working_dir: "./"

    - name: 'Terraform Plan'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: "./"
        args:
          -var-file="terraform.tfvars"
          -var "auth0_client_id=${{ secrets.AUTH0_CLIENT_ID }}"
          -var "auth0_client_secret=${{ secrets.AUTH0_CLIENT_SECRET }}"
          -var "environment=${{ env.ENVIRONMENT }}"

    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'apply'
        tf_actions_working_dir: "./"
        args:
          -var-file="terraform.tfvars"
          -var "auth0_client_id=${{ secrets.AUTH0_CLIENT_ID }}"
          -var "auth0_client_secret=${{ secrets.AUTH0_CLIENT_SECRET }}"
          -var "environment=${{ env.ENVIRONMENT }}"

  terraform-stage:
    name: 'Terraform STAGE'
    runs-on: ubuntu-latest
    environment: STAGE
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      STORAGE_ACCOUNT: tfdevopsstorage
      CONTAINER_NAME: tfstatecontainer-stage
      ENVIRONMENT: STAGE

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: "./"
        args:
          --backend-config="storage_account_name=${{ env.STORAGE_ACCOUNT }}"
          --backend-config="container_name=${{ env.CONTAINER_NAME }}"
          -var "environment=${{ env.ENVIRONMENT }}"

    - name: 'Terraform Validate'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'validate'
        tf_actions_working_dir: "./"

    - name: 'Terraform Plan'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: "./"
        args:
          -var-file="terraform.tfvars"
          -var "auth0_client_id=${{ secrets.AUTH0_CLIENT_ID }}"
          -var "auth0_client_secret=${{ secrets.AUTH0_CLIENT_SECRET }}"
          -var "environment=${{ env.ENVIRONMENT }}"

    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'apply'
        tf_actions_working_dir: "./"
        args:
          -var-file="terraform.tfvars"
          -var "auth0_client_id=${{ secrets.AUTH0_CLIENT_ID }}"
          -var "auth0_client_secret=${{ secrets.AUTH0_CLIENT_SECRET }}"
          -var "environment=${{ env.ENVIRONMENT }}"